/*
 * TigerGraph REST++ API
 * Title
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.karol_brejna_i.tigergraph.restppclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.karol_brejna_i.tigergraph.restppclient.model.AbortStatusItem;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AbortedQueryList
 */


public class AbortedQueryList {
  @SerializedName("aborted_queries")
  private List<AbortStatusItem> abortedQueries = null;

  public AbortedQueryList abortedQueries(List<AbortStatusItem> abortedQueries) {
    this.abortedQueries = abortedQueries;
    return this;
  }

  public AbortedQueryList addAbortedQueriesItem(AbortStatusItem abortedQueriesItem) {
    if (this.abortedQueries == null) {
      this.abortedQueries = new ArrayList<AbortStatusItem>();
    }
    this.abortedQueries.add(abortedQueriesItem);
    return this;
  }

   /**
   * Get abortedQueries
   * @return abortedQueries
  **/
  @Schema(description = "")
  public List<AbortStatusItem> getAbortedQueries() {
    return abortedQueries;
  }

  public void setAbortedQueries(List<AbortStatusItem> abortedQueries) {
    this.abortedQueries = abortedQueries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbortedQueryList abortedQueryList = (AbortedQueryList) o;
    return Objects.equals(this.abortedQueries, abortedQueryList.abortedQueries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abortedQueries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbortedQueryList {\n");
    
    sb.append("    abortedQueries: ").append(toIndentedString(abortedQueries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
