/*
 * TigerGraph REST++ API
 * Title
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.karol_brejna_i.tigergraph.restppclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.karol_brejna_i.tigergraph.restppclient.model.QueryStatusItem;
import io.github.karol_brejna_i.tigergraph.restppclient.model.Version;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * QueryStatusResponse
 */


public class QueryStatusResponse {
  @SerializedName("version")
  private Version version = null;

  @SerializedName("error")
  private Boolean error = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("results")
  private List<QueryStatusItem> results = new ArrayList<QueryStatusItem>();

  @SerializedName("unknown_requestid")
  private List<String> unknownRequestid = null;

  @SerializedName("code")
  private String code = null;

  public QueryStatusResponse version(Version version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(required = true, description = "")
  public Version getVersion() {
    return version;
  }

  public void setVersion(Version version) {
    this.version = version;
  }

  public QueryStatusResponse error(Boolean error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @Schema(required = true, description = "")
  public Boolean isError() {
    return error;
  }

  public void setError(Boolean error) {
    this.error = error;
  }

  public QueryStatusResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Schema(required = true, description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public QueryStatusResponse results(List<QueryStatusItem> results) {
    this.results = results;
    return this;
  }

  public QueryStatusResponse addResultsItem(QueryStatusItem resultsItem) {
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @Schema(required = true, description = "")
  public List<QueryStatusItem> getResults() {
    return results;
  }

  public void setResults(List<QueryStatusItem> results) {
    this.results = results;
  }

  public QueryStatusResponse unknownRequestid(List<String> unknownRequestid) {
    this.unknownRequestid = unknownRequestid;
    return this;
  }

  public QueryStatusResponse addUnknownRequestidItem(String unknownRequestidItem) {
    if (this.unknownRequestid == null) {
      this.unknownRequestid = new ArrayList<String>();
    }
    this.unknownRequestid.add(unknownRequestidItem);
    return this;
  }

   /**
   * If one or more of the provided query IDs (requestid) are invalid, the return JSON will include an unknown_requestid field containing all the invalid query IDs. If a query ID is marked as unknown, it means either the query does not exist or that it was not run in Detached Mode. 
   * @return unknownRequestid
  **/
  @Schema(description = "If one or more of the provided query IDs (requestid) are invalid, the return JSON will include an unknown_requestid field containing all the invalid query IDs. If a query ID is marked as unknown, it means either the query does not exist or that it was not run in Detached Mode. ")
  public List<String> getUnknownRequestid() {
    return unknownRequestid;
  }

  public void setUnknownRequestid(List<String> unknownRequestid) {
    this.unknownRequestid = unknownRequestid;
  }

  public QueryStatusResponse code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(required = true, description = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryStatusResponse queryStatusResponse = (QueryStatusResponse) o;
    return Objects.equals(this.version, queryStatusResponse.version) &&
        Objects.equals(this.error, queryStatusResponse.error) &&
        Objects.equals(this.message, queryStatusResponse.message) &&
        Objects.equals(this.results, queryStatusResponse.results) &&
        Objects.equals(this.unknownRequestid, queryStatusResponse.unknownRequestid) &&
        Objects.equals(this.code, queryStatusResponse.code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, error, message, results, unknownRequestid, code);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryStatusResponse {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    unknownRequestid: ").append(toIndentedString(unknownRequestid)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
